# Generated by Django 4.2.3 on 2023-08-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=20, null=True)),
                ('second_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('id_number', models.IntegerField(max_length=13, null=True)),
                ('work_number', models.IntegerField(max_length=10)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=7, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('street', models.CharField(max_length=20, null=True)),
                ('complex', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('postal_code', models.IntegerField(null=True)),
            ],
        ),
    ]
